/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rc.unesp.br.view;

import rc.unesp.br.controllers.Jogo;

/**
 *
 * @author Daniel
 */
public class MainView extends javax.swing.JFrame {
    private static Jogo jogo;
    private static MainView tela;
    
    /**
     * Creates new form MainView
     */
    public MainView() {              
        initComponents();
        jogo = new Jogo();
        jogo.inicializaJogo();
        setVisible(true);
    }
    
    public static void main(String[] args) {
        tela = new MainView();
    }
    private void finaliza(){
        jTextArea1.append("\n\nFim de jogo! Você ganhou em "+jogo.getChances()+" tiros!");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton50 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Batalha Naval");
        setMaximumSize(new java.awt.Dimension(806, 730));
        setMinimumSize(new java.awt.Dimension(806, 730));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(242, 242, 247));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new java.awt.GridLayout(7, 7));

        jButton1.setBackground(new java.awt.Color(58, 49, 90));
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(58, 49, 90));
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(58, 49, 90));
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setBackground(new java.awt.Color(58, 49, 90));
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setBackground(new java.awt.Color(58, 49, 90));
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setBackground(new java.awt.Color(58, 49, 90));
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setBackground(new java.awt.Color(58, 49, 90));
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setBackground(new java.awt.Color(58, 49, 90));
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setBackground(new java.awt.Color(58, 49, 90));
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jButton10.setBackground(new java.awt.Color(58, 49, 90));
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);

        jButton11.setBackground(new java.awt.Color(58, 49, 90));
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);

        jButton12.setBackground(new java.awt.Color(58, 49, 90));
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton12.setContentAreaFilled(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);

        jButton13.setBackground(new java.awt.Color(58, 49, 90));
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton13.setContentAreaFilled(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);

        jButton14.setBackground(new java.awt.Color(58, 49, 90));
        jButton14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);

        jButton15.setBackground(new java.awt.Color(58, 49, 90));
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);

        jButton16.setBackground(new java.awt.Color(58, 49, 90));
        jButton16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton16.setContentAreaFilled(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);

        jButton17.setBackground(new java.awt.Color(58, 49, 90));
        jButton17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton17.setContentAreaFilled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);

        jButton18.setBackground(new java.awt.Color(58, 49, 90));
        jButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton18.setContentAreaFilled(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);

        jButton19.setBackground(new java.awt.Color(58, 49, 90));
        jButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton19.setContentAreaFilled(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);

        jButton20.setBackground(new java.awt.Color(58, 49, 90));
        jButton20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton20.setContentAreaFilled(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);

        jButton21.setBackground(new java.awt.Color(58, 49, 90));
        jButton21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton21.setContentAreaFilled(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);

        jButton22.setBackground(new java.awt.Color(58, 49, 90));
        jButton22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton22.setContentAreaFilled(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton22);

        jButton23.setBackground(new java.awt.Color(58, 49, 90));
        jButton23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton23.setContentAreaFilled(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);

        jButton24.setBackground(new java.awt.Color(58, 49, 90));
        jButton24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton24.setContentAreaFilled(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton24);

        jButton25.setBackground(new java.awt.Color(58, 49, 90));
        jButton25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton25.setContentAreaFilled(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton25);

        jButton26.setBackground(new java.awt.Color(58, 49, 90));
        jButton26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton26.setContentAreaFilled(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton26);

        jButton27.setBackground(new java.awt.Color(58, 49, 90));
        jButton27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton27.setContentAreaFilled(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton27);

        jButton28.setBackground(new java.awt.Color(58, 49, 90));
        jButton28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton28.setContentAreaFilled(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton28);

        jButton29.setBackground(new java.awt.Color(58, 49, 90));
        jButton29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton29.setContentAreaFilled(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29);

        jButton30.setBackground(new java.awt.Color(58, 49, 90));
        jButton30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton30.setContentAreaFilled(false);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton30);

        jButton31.setBackground(new java.awt.Color(58, 49, 90));
        jButton31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton31.setContentAreaFilled(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31);

        jButton32.setBackground(new java.awt.Color(58, 49, 90));
        jButton32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton32.setContentAreaFilled(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton32);

        jButton33.setBackground(new java.awt.Color(58, 49, 90));
        jButton33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton33.setContentAreaFilled(false);
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33);

        jButton34.setBackground(new java.awt.Color(58, 49, 90));
        jButton34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton34.setContentAreaFilled(false);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton34);

        jButton35.setBackground(new java.awt.Color(58, 49, 90));
        jButton35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton35.setContentAreaFilled(false);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton35);

        jButton36.setBackground(new java.awt.Color(58, 49, 90));
        jButton36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton36.setContentAreaFilled(false);
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton36);

        jButton37.setBackground(new java.awt.Color(58, 49, 90));
        jButton37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton37.setContentAreaFilled(false);
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton37);

        jButton38.setBackground(new java.awt.Color(58, 49, 90));
        jButton38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton38.setContentAreaFilled(false);
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton38);

        jButton39.setBackground(new java.awt.Color(58, 49, 90));
        jButton39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton39.setContentAreaFilled(false);
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton39);

        jButton40.setBackground(new java.awt.Color(58, 49, 90));
        jButton40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton40.setContentAreaFilled(false);
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton40);

        jButton41.setBackground(new java.awt.Color(58, 49, 90));
        jButton41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton41.setContentAreaFilled(false);
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton41);

        jButton42.setBackground(new java.awt.Color(58, 49, 90));
        jButton42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton42.setContentAreaFilled(false);
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton42);

        jButton43.setBackground(new java.awt.Color(58, 49, 90));
        jButton43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton43.setContentAreaFilled(false);
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton43);

        jButton44.setBackground(new java.awt.Color(58, 49, 90));
        jButton44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton44.setContentAreaFilled(false);
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton44);

        jButton45.setBackground(new java.awt.Color(58, 49, 90));
        jButton45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton45.setContentAreaFilled(false);
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton45);

        jButton46.setBackground(new java.awt.Color(58, 49, 90));
        jButton46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton46.setContentAreaFilled(false);
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46);

        jButton47.setBackground(new java.awt.Color(58, 49, 90));
        jButton47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton47.setContentAreaFilled(false);
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton47);

        jButton48.setBackground(new java.awt.Color(58, 49, 90));
        jButton48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton48.setContentAreaFilled(false);
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton48);

        jButton49.setBackground(new java.awt.Color(58, 49, 90));
        jButton49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton49.setContentAreaFilled(false);
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton49);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 600);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/bg.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 100, 100);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bem vindo Jogador!");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 600, 680, 100);

        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/flag.png"))); // NOI18N
        jButton50.setText("Recomecar");
        jButton50.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton50.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton50);
        jButton50.setBounds(0, 600, 120, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setEnabled(false);
        if (jogo.atirar(0,0)){
            jTextArea1.append("\nVocê Acertou!");
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else{
            jTextArea1.append("\nVocê Errou!");
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        if (jogo.atirar(0,1)){
            jTextArea1.append("\nVocê Acertou!");
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else{
            jTextArea1.append("\nVocê Errou!");
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setEnabled(false);
        if (jogo.atirar(0,2)){
            jTextArea1.append("\nVocê Acertou!");
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else{
            jTextArea1.append("\nVocê Errou!");
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setEnabled(false);
        if (jogo.atirar(0,3)){
            jTextArea1.append("\nVocê Acertou!");
            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else{
            jTextArea1.append("\nVocê Errou!");
            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jButton5.setEnabled(false);
        if (jogo.atirar(0,4)){
            jTextArea1.append("\nVocê Acertou!");
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else{
            jTextArea1.append("\nVocê Errou!");
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setEnabled(false);
        if (jogo.atirar(0,5)){
            jTextArea1.append("\nVocê Acertou!");
            jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else{
            jTextArea1.append("\nVocê Errou!");
            jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());          
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jButton7.setEnabled(false);
        if (jogo.atirar(0, 6)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jButton8.setEnabled(false);
        if (jogo.atirar(1, 0)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jButton9.setEnabled(false);
        if (jogo.atirar(1, 1)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jButton10.setEnabled(false);
        if (jogo.atirar(1, 2)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jButton11.setEnabled(false);
        if (jogo.atirar(1, 3)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        jButton12.setEnabled(false);
        if (jogo.atirar(1, 4)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        jButton13.setEnabled(false);
        if (jogo.atirar(1, 5)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton13.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        jButton14.setEnabled(false);
        if (jogo.atirar(1, 6)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton14.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton14.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jButton15.setEnabled(false);
        if (jogo.atirar(2, 0)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton15.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        jButton16.setEnabled(false);
        if (jogo.atirar(2, 1)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton16.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton16.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        jButton17.setEnabled(false);
        if (jogo.atirar(2, 2)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton17.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton17.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        jButton18.setEnabled(false);
        if (jogo.atirar(2, 3)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton18.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton18.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        jButton19.setEnabled(false);
        if (jogo.atirar(2, 4)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton19.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton19.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        jButton20.setEnabled(false);
        if (jogo.atirar(2, 5)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton20.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton20.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        jButton21.setEnabled(false);
        if (jogo.atirar(2, 6)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton21.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton21.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        jButton22.setEnabled(false);
        if (jogo.atirar(3, 0)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton22.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton22.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        jButton23.setEnabled(false);
        if (jogo.atirar(3, 1)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton23.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton23.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        jButton24.setEnabled(false);
        if (jogo.atirar(3, 2)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton24.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton24.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        jButton25.setEnabled(false);
        if (jogo.atirar(3, 3)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton25.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton25.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        jButton26.setEnabled(false);
        if (jogo.atirar(3, 4)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton26.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton26.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        jButton27.setEnabled(false);
        if (jogo.atirar(3, 5)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton27.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton27.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        jButton28.setEnabled(false);
        if (jogo.atirar(3, 6)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton28.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton28.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        jButton29.setEnabled(false);
        if (jogo.atirar(4, 0)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton29.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton29.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        jButton30.setEnabled(false);
        if (jogo.atirar(4, 1)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton30.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton30.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        jButton31.setEnabled(false);
        if (jogo.atirar(4, 2)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton31.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton31.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        jButton32.setEnabled(false);
        if (jogo.atirar(4, 3)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton32.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton32.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        jButton33.setEnabled(false);
        if (jogo.atirar(4, 4)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton33.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton33.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        jButton34.setEnabled(false);
        if (jogo.atirar(4, 5)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton34.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton34.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        jButton35.setEnabled(false);
        if (jogo.atirar(4, 6)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton35.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton35.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        jButton36.setEnabled(false);
        if (jogo.atirar(5, 0)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton36.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton36.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        jButton37.setEnabled(false);
        if (jogo.atirar(5, 1)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton37.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton37.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        jButton38.setEnabled(false);
        if (jogo.atirar(5, 2)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton38.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton38.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        jButton39.setEnabled(false);
        if (jogo.atirar(5, 3)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton39.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton39.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        jButton40.setEnabled(false);
        if (jogo.atirar(5, 4)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton40.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton40.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        jButton41.setEnabled(false);
        if (jogo.atirar(5, 5)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton41.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton41.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        jButton42.setEnabled(false);
        if (jogo.atirar(5, 6)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton42.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton42.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        jButton43.setEnabled(false);
        if (jogo.atirar(6, 0)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton43.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton43.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        jButton44.setEnabled(false);
        if (jogo.atirar(6, 1)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton44.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton44.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        jButton45.setEnabled(false);
        if (jogo.atirar(6, 2)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton45.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton45.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        jButton46.setEnabled(false);
        if (jogo.atirar(6, 3)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton46.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton46.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        jButton47.setEnabled(false);
        if (jogo.atirar(6, 4)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton47.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton47.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        jButton48.setEnabled(false);
        if (jogo.atirar(6, 5)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton48.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton48.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        jButton49.setEnabled(false);
        if (jogo.atirar(6, 6)) {
            jTextArea1.append("\nVocê Acertou!");
            jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            jButton49.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/fogo.png")));
            if (jogo.isFim()) finaliza();
        } else {
            jTextArea1.append("\nVocê Errou!");
            jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
            jButton49.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/rc/unesp/br/resources/agua.png")));
        }
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
        jogo = null;
        tela.dispose();
        tela = null;
        tela = new MainView();
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
